"""initial site domain foundation

Revision ID: 0001_site_domain
Revises:
Create Date: 2026-08-10 10:30:02.391638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_site_domain"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_projections",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("primary_email", sa.String(length=320), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column("central_revision", sa.Integer(), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("person_id", name=op.f("pk_site_person_projections")),
    )
    op.create_table(
        "sites",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("central_revision", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("site_id", name=op.f("pk_site_sites")),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_devices_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("device_id", name=op.f("pk_site_devices")),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_events_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_site_events")),
    )
    op.create_table(
        "storage_targets",
        sa.Column("storage_target_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "storage_type",
            sa.Enum(
                "local_filesystem",
                "mounted_filesystem",
                "archive",
                name="storagetype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("root_path", sa.String(length=2048), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("primary_media", sa.Boolean(), nullable=False),
        sa.Column(
            "health",
            sa.Enum(
                "unknown",
                "healthy",
                "warning",
                "critical",
                "unavailable",
                "read_only",
                "write_failure",
                name="storagehealth",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("warning_free_bytes", sa.BigInteger(), nullable=True),
        sa.Column("critical_free_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "root_path LIKE '/%%'", name=op.f("ck_site_storage_targets_root_path_absolute")
        ),
        sa.CheckConstraint(
            "critical_free_bytes IS NULL OR critical_free_bytes >= 0",
            name=op.f("ck_site_storage_targets_critical_nonnegative"),
        ),
        sa.CheckConstraint(
            "warning_free_bytes IS NULL OR critical_free_bytes IS NULL OR "
            "warning_free_bytes >= critical_free_bytes",
            name=op.f("ck_site_storage_targets_threshold_order"),
        ),
        sa.CheckConstraint(
            "warning_free_bytes IS NULL OR warning_free_bytes >= 0",
            name=op.f("ck_site_storage_targets_warning_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_storage_targets_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("storage_target_id", name=op.f("pk_site_storage_targets")),
        sa.UniqueConstraint(
            "site_id", "display_name", name=op.f("uq_site_storage_targets_site_id")
        ),
    )
    op.create_index(
        "uq_site_one_primary_storage_target",
        "storage_targets",
        ["site_id"],
        unique=True,
        postgresql_where=sa.text("primary_media AND enabled"),
    )
    op.create_table(
        "audit_records",
        sa.Column("audit_record_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("before_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_audit_records_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_audit_records_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("audit_record_id", name=op.f("pk_site_audit_records")),
    )
    op.create_table(
        "event_participations",
        sa.Column("event_participation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_event_participations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person_projections.person_id"],
            name=op.f("fk_site_event_participations_person_id_person_projections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "event_participation_id", name=op.f("pk_site_event_participations")
        ),
        sa.UniqueConstraint(
            "event_id", "person_id", name=op.f("uq_site_event_participations_event_id")
        ),
    )
    op.create_table(
        "media_objects",
        sa.Column("media_object_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("storage_target_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=2048), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "presentation",
                "presentation_version",
                "open_file",
                "derivative",
                "pdf_derivative",
                "preview",
                "thumbnail",
                "signage",
                "ingestion_staging",
                "temporary_processing",
                "archive",
                name="mediacategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("source_media_object_id", sa.UUID(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "object_key !~ '(^/|^\\\\|(^|/)\\.\\.(/|$))'",
            name=op.f("ck_site_media_objects_object_key_relative"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_site_media_objects_size_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_media_objects_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_media_objects_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_media_object_id"],
            ["media_objects.media_object_id"],
            name=op.f("fk_site_media_objects_source_media_object_id_media_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["storage_target_id"],
            ["storage_targets.storage_target_id"],
            name=op.f("fk_site_media_objects_storage_target_id_storage_targets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("media_object_id", name=op.f("pk_site_media_objects")),
        sa.UniqueConstraint(
            "storage_target_id", "object_key", name=op.f("uq_site_media_objects_storage_target_id")
        ),
    )
    op.create_table(
        "rooms",
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_rooms_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_rooms_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("room_id", name=op.f("pk_site_rooms")),
        sa.UniqueConstraint("site_id", "label", name=op.f("uq_site_rooms_site_id")),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_sessions_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_site_sessions")),
    )
    op.create_table(
        "sync_events",
        sa.Column("sync_event_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "central",
                "site",
                "import",
                "external",
                name="sourcesystem",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_site_sync_events_attempt_count_nonnegative")
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_site_sync_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_sync_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_sync_events_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sync_event_id", name=op.f("pk_site_sync_events")),
        sa.UniqueConstraint(
            "source_system", "idempotency_key", name=op.f("uq_site_sync_events_source_system")
        ),
    )
    op.create_table(
        "device_assignments",
        sa.Column("device_assignment_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "primary",
                "backup",
                "auxiliary",
                name="devicerole",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_site_device_assignments_valid_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_site_device_assignments_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.room_id"],
            name=op.f("fk_site_device_assignments_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("device_assignment_id", name=op.f("pk_site_device_assignments")),
    )
    op.create_table(
        "presentations",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_presentations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_site_presentations_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("presentation_id", name=op.f("pk_site_presentations")),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("processing_job_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("media_object_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "retrying",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("required_capability", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "max_retries >= 0", name=op.f("ck_site_processing_jobs_max_retries_nonnegative")
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_site_processing_jobs_progress_range")
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_site_processing_jobs_retry_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_objects.media_object_id"],
            name=op.f("fk_site_processing_jobs_media_object_id_media_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_processing_jobs_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("processing_job_id", name=op.f("pk_site_processing_jobs")),
    )
    op.create_table(
        "room_assignments",
        sa.Column("room_assignment_id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_site_room_assignments_valid_time_range"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.room_id"],
            name=op.f("fk_site_room_assignments_room_id_rooms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_site_room_assignments_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("room_assignment_id", name=op.f("pk_site_room_assignments")),
    )
    op.create_table(
        "session_participants",
        sa.Column("session_participant_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_participation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_participation_id"],
            ["event_participations.event_participation_id"],
            name=op.f("fk_site_session_participants_event_participation_id_event_participations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_site_session_participants_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "session_participant_id", name=op.f("pk_site_session_participants")
        ),
        sa.UniqueConstraint(
            "session_id",
            "event_participation_id",
            "role",
            name=op.f("uq_site_session_participants_session_id"),
        ),
    )
    op.create_table(
        "transfer_jobs",
        sa.Column("transfer_job_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("media_object_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "retrying",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "max_retries >= 0", name=op.f("ck_site_transfer_jobs_max_retries_nonnegative")
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_site_transfer_jobs_progress_range")
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_site_transfer_jobs_retry_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_objects.media_object_id"],
            name=op.f("fk_site_transfer_jobs_media_object_id_media_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_transfer_jobs_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("transfer_job_id", name=op.f("pk_site_transfer_jobs")),
    )
    op.create_table(
        "presentation_presenters",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("session_participant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.presentation_id"],
            name=op.f("fk_site_presentation_presenters_presentation_id_presentations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_participant_id"],
            ["session_participants.session_participant_id"],
            name=op.f(
                "fk_site_presentation_presenters_session_participant_id_session_participants"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "presentation_id",
            "session_participant_id",
            name=op.f("pk_site_presentation_presenters"),
        ),
    )
    op.create_table(
        "presentation_versions",
        sa.Column("presentation_version_id", sa.UUID(), nullable=False),
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1",
            name=op.f("ck_site_presentation_versions_version_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.presentation_id"],
            name=op.f("fk_site_presentation_versions_presentation_id_presentations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "presentation_version_id", name=op.f("pk_site_presentation_versions")
        ),
        sa.UniqueConstraint(
            "presentation_id",
            "version_number",
            name=op.f("uq_site_presentation_versions_presentation_id"),
        ),
    )
    op.create_table(
        "presentation_assets",
        sa.Column("presentation_asset_id", sa.UUID(), nullable=False),
        sa.Column("presentation_version_id", sa.UUID(), nullable=False),
        sa.Column("media_object_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "original",
                "derivative",
                name="assetkind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("source_asset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'original' AND source_asset_id IS NULL) OR "
            "(kind = 'derivative' AND source_asset_id IS NOT NULL)",
            name=op.f("ck_site_presentation_assets_derivative_source"),
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_objects.media_object_id"],
            name=op.f("fk_site_presentation_assets_media_object_id_media_objects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["presentation_version_id"],
            ["presentation_versions.presentation_version_id"],
            name=op.f("fk_site_presentation_assets_presentation_version_id_presentation_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["presentation_assets.presentation_asset_id"],
            name=op.f("fk_site_presentation_assets_source_asset_id_presentation_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("presentation_asset_id", name=op.f("pk_site_presentation_assets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presentation_assets")
    op.drop_table("presentation_versions")
    op.drop_table("presentation_presenters")
    op.drop_table("transfer_jobs")
    op.drop_table("session_participants")
    op.drop_table("room_assignments")
    op.drop_table("processing_jobs")
    op.drop_table("presentations")
    op.drop_table("device_assignments")
    op.drop_table("sync_events")
    op.drop_table("sessions")
    op.drop_table("rooms")
    op.drop_table("media_objects")
    op.drop_table("event_participations")
    op.drop_table("audit_records")
    op.drop_index(
        "uq_site_one_primary_storage_target",
        table_name="storage_targets",
        postgresql_where=sa.text("primary_media AND enabled"),
    )
    op.drop_table("storage_targets")
    op.drop_table("events")
    op.drop_table("devices")
    op.drop_table("sites")
    op.drop_table("person_projections")
    # ### end Alembic commands ###
