"""add site durable jobs and outbox

Revision ID: 6ed903da8ed5
Revises: 0001_site_domain
Create Date: 2026-08-10 11:28:29.247741
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6ed903da8ed5"
down_revision: str | Sequence[str] | None = "0001_site_domain"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_identities",
        sa.Column("worker_id", sa.String(length=255), nullable=False),
        sa.Column("worker_type", sa.String(length=100), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("service_role", sa.String(length=100), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("pk_site_worker_identities")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("outbox_event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "central",
                "site",
                "import",
                "external",
                name="sourcesystem",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retry_wait",
                "cancelled",
                "exhausted",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.String(length=2048), nullable=True),
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_site_outbox_events_attempt_count_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_site_outbox_events_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_site_outbox_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_site_outbox_events_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("outbox_event_id", name=op.f("pk_site_outbox_events")),
        sa.UniqueConstraint(
            "source_system", "idempotency_key", name=op.f("uq_site_outbox_events_source_system")
        ),
    )
    op.create_index(
        "ix_site_outbox_claim",
        "outbox_events",
        ["status", "available_at", "priority"],
        unique=False,
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "processing_jobs",
        sa.Column("payload_schema_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "processing_jobs", sa.Column("priority", sa.Integer(), server_default="200", nullable=False)
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "required_capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "processing_jobs", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "processing_jobs",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "processing_jobs",
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "processing_jobs", sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "processing_jobs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "processing_jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("processing_jobs", sa.Column("error_code", sa.String(length=100), nullable=True))
    op.add_column("processing_jobs", sa.Column("last_error", sa.String(length=2048), nullable=True))
    op.add_column(
        "processing_jobs",
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_constraint(op.f("ck_site_processing_jobs_jobstatus"), "processing_jobs", type_="check")
    op.execute(
        "UPDATE processing_jobs SET status = CASE status "
        "WHEN 'queued' THEN 'pending' WHEN 'retrying' THEN 'retry_wait' ELSE status END, "
        "attempt_count = retry_count, max_attempts = GREATEST(max_retries, 1), "
        "claimed_by_worker_id = worker_id, last_error = LEFT(error_detail, 2048), "
        "required_capabilities = CASE WHEN required_capability IS NULL THEN '[]'::jsonb "
        "ELSE jsonb_build_array(required_capability) END"
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_jobstatus"),
        "processing_jobs",
        "status IN ('pending', 'running', 'succeeded', 'failed', "
        "'retry_wait', 'cancelled', 'exhausted')",
    )
    op.create_index(
        "ix_site_processing_claim",
        "processing_jobs",
        ["status", "next_attempt_at", "priority"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_site_processing_jobs_job_type"), "processing_jobs", ["job_type", "idempotency_key"]
    )
    op.drop_constraint(
        op.f("ck_site_processing_jobs_max_retries_nonnegative"), "processing_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_site_processing_jobs_retry_count_nonnegative"), "processing_jobs", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_attempt_count_nonnegative"),
        "processing_jobs",
        "attempt_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_max_attempts_positive"),
        "processing_jobs",
        "max_attempts >= 1",
    )
    op.drop_column("processing_jobs", "error_detail")
    op.drop_column("processing_jobs", "required_capability")
    op.drop_column("processing_jobs", "max_retries")
    op.drop_column("processing_jobs", "retry_count")
    op.drop_column("processing_jobs", "worker_id")
    for column_name in (
        "payload",
        "payload_schema_version",
        "priority",
        "required_capabilities",
        "attempt_count",
        "max_attempts",
        "next_attempt_at",
    ):
        op.alter_column("processing_jobs", column_name, server_default=None)
    op.add_column(
        "transfer_jobs",
        sa.Column("transfer_type", sa.String(length=100), server_default="legacy", nullable=False),
    )
    op.add_column(
        "transfer_jobs",
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "transfer_jobs",
        sa.Column("payload_schema_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "transfer_jobs", sa.Column("priority", sa.Integer(), server_default="200", nullable=False)
    )
    op.add_column(
        "transfer_jobs",
        sa.Column(
            "required_capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[\"transfer\"]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "transfer_jobs", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "transfer_jobs",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "transfer_jobs", sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False)
    )
    op.add_column(
        "transfer_jobs",
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "transfer_jobs", sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "transfer_jobs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "transfer_jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("transfer_jobs", sa.Column("error_code", sa.String(length=100), nullable=True))
    op.add_column("transfer_jobs", sa.Column("last_error", sa.String(length=2048), nullable=True))
    op.add_column(
        "transfer_jobs",
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_constraint(op.f("ck_site_transfer_jobs_jobstatus"), "transfer_jobs", type_="check")
    op.execute(
        "UPDATE transfer_jobs SET status = CASE status WHEN 'queued' THEN 'pending' "
        "WHEN 'retrying' THEN 'retry_wait' ELSE status END, attempt_count = retry_count, "
        "max_attempts = GREATEST(max_retries, 1), claimed_by_worker_id = worker_id, "
        "last_error = LEFT(error_detail, 2048)"
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_jobstatus"),
        "transfer_jobs",
        "status IN ('pending', 'running', 'succeeded', 'failed', "
        "'retry_wait', 'cancelled', 'exhausted')",
    )
    op.create_index(
        "ix_site_transfer_claim",
        "transfer_jobs",
        ["status", "next_attempt_at", "priority"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_site_transfer_jobs_transfer_type"),
        "transfer_jobs",
        ["transfer_type", "idempotency_key"],
    )
    op.drop_constraint(
        op.f("ck_site_transfer_jobs_max_retries_nonnegative"), "transfer_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_site_transfer_jobs_retry_count_nonnegative"), "transfer_jobs", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_attempt_count_nonnegative"),
        "transfer_jobs",
        "attempt_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_max_attempts_positive"), "transfer_jobs", "max_attempts >= 1"
    )
    op.drop_column("transfer_jobs", "error_detail")
    op.drop_column("transfer_jobs", "max_retries")
    op.drop_column("transfer_jobs", "retry_count")
    op.drop_column("transfer_jobs", "worker_id")
    for column_name in (
        "transfer_type",
        "payload",
        "payload_schema_version",
        "priority",
        "required_capabilities",
        "attempt_count",
        "max_attempts",
        "next_attempt_at",
    ):
        op.alter_column("transfer_jobs", column_name, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer_jobs",
        sa.Column("worker_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transfer_jobs",
        sa.Column(
            "retry_count", sa.INTEGER(), server_default="0", autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "transfer_jobs",
        sa.Column(
            "max_retries", sa.INTEGER(), server_default="3", autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "transfer_jobs", sa.Column("error_detail", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(op.f("ck_site_transfer_jobs_jobstatus"), "transfer_jobs", type_="check")
    op.execute(
        "UPDATE transfer_jobs SET status = CASE status WHEN 'pending' THEN 'queued' "
        "WHEN 'retry_wait' THEN 'retrying' WHEN 'exhausted' THEN 'failed' ELSE status END, "
        "retry_count = attempt_count, max_retries = GREATEST(max_attempts - 1, 0), "
        "worker_id = claimed_by_worker_id, error_detail = last_error"
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_jobstatus"),
        "transfer_jobs",
        "status IN ('queued', 'running', 'succeeded', 'failed', 'retrying', 'cancelled')",
    )
    op.drop_constraint(
        op.f("ck_site_transfer_jobs_max_attempts_positive"), "transfer_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_site_transfer_jobs_attempt_count_nonnegative"), "transfer_jobs", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_retry_count_nonnegative"), "transfer_jobs", "retry_count >= 0"
    )
    op.create_check_constraint(
        op.f("ck_site_transfer_jobs_max_retries_nonnegative"), "transfer_jobs", "max_retries >= 0"
    )
    op.drop_constraint(op.f("uq_site_transfer_jobs_transfer_type"), "transfer_jobs", type_="unique")
    op.drop_index("ix_site_transfer_claim", table_name="transfer_jobs")
    op.drop_column("transfer_jobs", "error_metadata")
    op.drop_column("transfer_jobs", "last_error")
    op.drop_column("transfer_jobs", "error_code")
    op.drop_column("transfer_jobs", "heartbeat_at")
    op.drop_column("transfer_jobs", "lease_expires_at")
    op.drop_column("transfer_jobs", "claimed_by_worker_id")
    op.drop_column("transfer_jobs", "next_attempt_at")
    op.drop_column("transfer_jobs", "max_attempts")
    op.drop_column("transfer_jobs", "attempt_count")
    op.drop_column("transfer_jobs", "idempotency_key")
    op.drop_column("transfer_jobs", "required_capabilities")
    op.drop_column("transfer_jobs", "priority")
    op.drop_column("transfer_jobs", "payload_schema_version")
    op.drop_column("transfer_jobs", "payload")
    op.drop_column("transfer_jobs", "transfer_type")
    op.add_column(
        "processing_jobs",
        sa.Column("worker_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "retry_count", sa.INTEGER(), server_default="0", autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "max_retries", sa.INTEGER(), server_default="3", autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "required_capability", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "processing_jobs", sa.Column("error_detail", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(op.f("ck_site_processing_jobs_jobstatus"), "processing_jobs", type_="check")
    op.execute(
        "UPDATE processing_jobs SET status = CASE status WHEN 'pending' THEN 'queued' "
        "WHEN 'retry_wait' THEN 'retrying' WHEN 'exhausted' THEN 'failed' ELSE status END, "
        "retry_count = attempt_count, max_retries = GREATEST(max_attempts - 1, 0), "
        "worker_id = claimed_by_worker_id, error_detail = last_error, "
        "required_capability = required_capabilities ->> 0"
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_jobstatus"),
        "processing_jobs",
        "status IN ('queued', 'running', 'succeeded', 'failed', 'retrying', 'cancelled')",
    )
    op.drop_constraint(
        op.f("ck_site_processing_jobs_max_attempts_positive"), "processing_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_site_processing_jobs_attempt_count_nonnegative"), "processing_jobs", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_retry_count_nonnegative"),
        "processing_jobs",
        "retry_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_site_processing_jobs_max_retries_nonnegative"),
        "processing_jobs",
        "max_retries >= 0",
    )
    op.drop_constraint(op.f("uq_site_processing_jobs_job_type"), "processing_jobs", type_="unique")
    op.drop_index("ix_site_processing_claim", table_name="processing_jobs")
    op.drop_column("processing_jobs", "error_metadata")
    op.drop_column("processing_jobs", "last_error")
    op.drop_column("processing_jobs", "error_code")
    op.drop_column("processing_jobs", "heartbeat_at")
    op.drop_column("processing_jobs", "lease_expires_at")
    op.drop_column("processing_jobs", "claimed_by_worker_id")
    op.drop_column("processing_jobs", "next_attempt_at")
    op.drop_column("processing_jobs", "max_attempts")
    op.drop_column("processing_jobs", "attempt_count")
    op.drop_column("processing_jobs", "idempotency_key")
    op.drop_column("processing_jobs", "required_capabilities")
    op.drop_column("processing_jobs", "priority")
    op.drop_column("processing_jobs", "payload_schema_version")
    op.drop_column("processing_jobs", "payload")
    op.drop_index("ix_site_outbox_claim", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("worker_identities")
    # ### end Alembic commands ###
