"""initial central domain foundation

Revision ID: 0001_central_domain
Revises:
Create Date: 2026-08-10 10:30:00.745602
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_central_domain"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("primary_email", sa.String(length=320), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_central_persons_revision_positive")),
        sa.PrimaryKeyConstraint("person_id", name=op.f("pk_central_persons")),
    )
    op.create_table(
        "sites",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("site_id", name=op.f("pk_central_sites")),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("owning_site_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owning_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_events_owning_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_central_events")),
    )
    op.create_table(
        "person_identity_links",
        sa.Column("identity_link_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("linked_person_id", sa.UUID(), nullable=False),
        sa.Column("link_type", sa.String(length=64), nullable=False),
        sa.Column("administrator_confirmed", sa.Boolean(), nullable=False),
        sa.Column("confirmed_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "person_id <> linked_person_id",
            name=op.f("ck_central_person_identity_links_different_people"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_person_id"],
            ["persons.person_id"],
            name=op.f("fk_central_person_identity_links_linked_person_id_persons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
            name=op.f("fk_central_person_identity_links_person_id_persons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("identity_link_id", name=op.f("pk_central_person_identity_links")),
        sa.UniqueConstraint(
            "person_id",
            "linked_person_id",
            "link_type",
            name=op.f("uq_central_person_identity_links_person_id"),
        ),
    )
    op.create_table(
        "person_identity_signals",
        sa.Column("identity_signal_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum(
                "primary_email",
                "alternate_email",
                "phone",
                "organization",
                "external_id",
                "import_id",
                name="identitysignaltype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("normalized_value", sa.String(length=512), nullable=False),
        sa.Column("source_namespace", sa.String(length=255), nullable=True),
        sa.Column("source_identifier", sa.String(length=512), nullable=True),
        sa.Column("administrator_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
            name=op.f("fk_central_person_identity_signals_person_id_persons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "identity_signal_id", name=op.f("pk_central_person_identity_signals")
        ),
    )
    op.create_index(
        "ix_central_identity_signal_lookup",
        "person_identity_signals",
        ["signal_type", "normalized_value"],
        unique=False,
    )
    op.create_table(
        "audit_records",
        sa.Column("audit_record_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("before_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_audit_records_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_audit_records_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("audit_record_id", name=op.f("pk_central_audit_records")),
    )
    op.create_table(
        "event_participations",
        sa.Column("event_participation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_event_participations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.person_id"],
            name=op.f("fk_central_event_participations_person_id_persons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "event_participation_id", name=op.f("pk_central_event_participations")
        ),
        sa.UniqueConstraint(
            "event_id", "person_id", name=op.f("uq_central_event_participations_event_id")
        ),
    )
    op.create_table(
        "media_object_replicas",
        sa.Column("media_object_id", sa.UUID(), nullable=False),
        sa.Column("authoritative_site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "presentation",
                "presentation_version",
                "open_file",
                "derivative",
                "pdf_derivative",
                "preview",
                "thumbnail",
                "signage",
                "ingestion_staging",
                "temporary_processing",
                "archive",
                name="mediacategory",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=2048), nullable=False),
        sa.Column("content_hash", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["authoritative_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_media_object_replicas_authoritative_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_media_object_replicas_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("media_object_id", name=op.f("pk_central_media_object_replicas")),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_sessions_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_central_sessions")),
    )
    op.create_table(
        "sync_events",
        sa.Column("sync_event_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "central",
                "site",
                "import",
                "external",
                name="sourcesystem",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("owning_site_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "sync_state",
            sa.Enum(
                "local",
                "pending",
                "synchronizing",
                "synchronized",
                "conflict",
                "failed",
                name="syncstate",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_central_sync_events_attempt_count_nonnegative")
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_central_sync_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_sync_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owning_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_sync_events_owning_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sync_event_id", name=op.f("pk_central_sync_events")),
        sa.UniqueConstraint(
            "source_system", "idempotency_key", name=op.f("uq_central_sync_events_source_system")
        ),
    )
    op.create_table(
        "presentations",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_presentations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_central_presentations_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("presentation_id", name=op.f("pk_central_presentations")),
    )
    op.create_table(
        "session_participants",
        sa.Column("session_participant_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_participation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_participation_id"],
            ["event_participations.event_participation_id"],
            name=op.f(
                "fk_central_session_participants_event_participation_id_event_participations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_central_session_participants_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "session_participant_id", name=op.f("pk_central_session_participants")
        ),
        sa.UniqueConstraint(
            "session_id",
            "event_participation_id",
            "role",
            name=op.f("uq_central_session_participants_session_id"),
        ),
    )
    op.create_table(
        "presentation_presenters",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("session_participant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.presentation_id"],
            name=op.f("fk_central_presentation_presenters_presentation_id_presentations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_participant_id"],
            ["session_participants.session_participant_id"],
            name=op.f(
                "fk_central_presentation_presenters_session_participant_id_session_participants"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "presentation_id",
            "session_participant_id",
            name=op.f("pk_central_presentation_presenters"),
        ),
    )
    op.create_table(
        "presentation_versions",
        sa.Column("presentation_version_id", sa.UUID(), nullable=False),
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1",
            name=op.f("ck_central_presentation_versions_version_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.presentation_id"],
            name=op.f("fk_central_presentation_versions_presentation_id_presentations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "presentation_version_id", name=op.f("pk_central_presentation_versions")
        ),
        sa.UniqueConstraint(
            "presentation_id",
            "version_number",
            name=op.f("uq_central_presentation_versions_presentation_id"),
        ),
    )
    op.create_table(
        "presentation_assets",
        sa.Column("presentation_asset_id", sa.UUID(), nullable=False),
        sa.Column("presentation_version_id", sa.UUID(), nullable=False),
        sa.Column("media_object_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "original",
                "derivative",
                name="assetkind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("source_asset_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'original' AND source_asset_id IS NULL) OR "
            "(kind = 'derivative' AND source_asset_id IS NOT NULL)",
            name=op.f("ck_central_presentation_assets_derivative_source"),
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_object_replicas.media_object_id"],
            name=op.f("fk_central_presentation_assets_media_object_id_media_object_replicas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["presentation_version_id"],
            ["presentation_versions.presentation_version_id"],
            name=op.f(
                "fk_central_presentation_assets_presentation_version_id_presentation_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["presentation_assets.presentation_asset_id"],
            name=op.f("fk_central_presentation_assets_source_asset_id_presentation_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "presentation_asset_id", name=op.f("pk_central_presentation_assets")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presentation_assets")
    op.drop_table("presentation_versions")
    op.drop_table("presentation_presenters")
    op.drop_table("session_participants")
    op.drop_table("presentations")
    op.drop_table("sync_events")
    op.drop_table("sessions")
    op.drop_table("media_object_replicas")
    op.drop_table("event_participations")
    op.drop_table("audit_records")
    op.drop_index("ix_central_identity_signal_lookup", table_name="person_identity_signals")
    op.drop_table("person_identity_signals")
    op.drop_table("person_identity_links")
    op.drop_table("events")
    op.drop_table("sites")
    op.drop_table("persons")
    # ### end Alembic commands ###
