"""add central durable jobs and outbox

Revision ID: ad875b02aaed
Revises: 0001_central_domain
Create Date: 2026-08-10 11:28:27.700571
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ad875b02aaed"
down_revision: str | Sequence[str] | None = "0001_central_domain"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_identities",
        sa.Column("worker_id", sa.String(length=255), nullable=False),
        sa.Column("worker_type", sa.String(length=100), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("service_role", sa.String(length=100), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("pk_central_worker_identities")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("outbox_event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("owning_site_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "central",
                "site",
                "import",
                "external",
                name="sourcesystem",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retry_wait",
                "cancelled",
                "exhausted",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.String(length=2048), nullable=True),
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_central_outbox_events_attempt_count_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_central_outbox_events_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_central_outbox_events_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owning_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_outbox_events_owning_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("outbox_event_id", name=op.f("pk_central_outbox_events")),
        sa.UniqueConstraint(
            "source_system", "idempotency_key", name=op.f("uq_central_outbox_events_source_system")
        ),
    )
    op.create_index(
        "ix_central_outbox_claim",
        "outbox_events",
        ["status", "available_at", "priority"],
        unique=False,
    )
    op.create_table(
        "processing_jobs",
        sa.Column("processing_job_id", sa.UUID(), nullable=False),
        sa.Column("owning_site_id", sa.UUID(), nullable=True),
        sa.Column("media_object_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retry_wait",
                "cancelled",
                "exhausted",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("required_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.String(length=2048), nullable=True),
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_central_processing_jobs_attempt_count_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_central_processing_jobs_max_attempts_positive")
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100",
            name=op.f("ck_central_processing_jobs_progress_range"),
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_object_replicas.media_object_id"],
            name=op.f("fk_central_processing_jobs_media_object_id_media_object_replicas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owning_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_processing_jobs_owning_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("processing_job_id", name=op.f("pk_central_processing_jobs")),
        sa.UniqueConstraint(
            "job_type", "idempotency_key", name=op.f("uq_central_processing_jobs_job_type")
        ),
    )
    op.create_index(
        "ix_central_processing_claim",
        "processing_jobs",
        ["status", "next_attempt_at", "priority"],
        unique=False,
    )
    op.create_table(
        "transfer_jobs",
        sa.Column("transfer_job_id", sa.UUID(), nullable=False),
        sa.Column("owning_site_id", sa.UUID(), nullable=True),
        sa.Column("media_object_id", sa.UUID(), nullable=True),
        sa.Column("transfer_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retry_wait",
                "cancelled",
                "exhausted",
                name="jobstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("required_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_by_worker_id", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.String(length=2048), nullable=True),
        sa.Column("error_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_central_transfer_jobs_attempt_count_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_central_transfer_jobs_max_attempts_positive")
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100",
            name=op.f("ck_central_transfer_jobs_progress_range"),
        ),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_object_replicas.media_object_id"],
            name=op.f("fk_central_transfer_jobs_media_object_id_media_object_replicas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owning_site_id"],
            ["sites.site_id"],
            name=op.f("fk_central_transfer_jobs_owning_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("transfer_job_id", name=op.f("pk_central_transfer_jobs")),
        sa.UniqueConstraint(
            "transfer_type", "idempotency_key", name=op.f("uq_central_transfer_jobs_transfer_type")
        ),
    )
    op.create_index(
        "ix_central_transfer_claim",
        "transfer_jobs",
        ["status", "next_attempt_at", "priority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_central_transfer_claim", table_name="transfer_jobs")
    op.drop_table("transfer_jobs")
    op.drop_index("ix_central_processing_claim", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index("ix_central_outbox_claim", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("worker_identities")
    # ### end Alembic commands ###
