[global]
 server role = standalone server
 security = user
 netbios name = ${UPM_SMB_HOSTNAME}
 server string = ${UPM_SMB_HOSTNAME}
 map to guest = Never
 restrict anonymous = 2
 server min protocol = SMB3_00
 server max protocol = SMB3_11
 client min protocol = SMB3_00
 ntlm auth = ntlmv2-only
 lanman auth = no
 client lanman auth = no
 client plaintext auth = no
 smb encrypt = desired
 disable netbios = yes
 server services = -dns, -nbt
 interfaces = ${UPM_SMB_INTERFACES}
 bind interfaces only = yes
 passdb backend = tdbsam
 log level = 1 auth_audit:2
 logging = stdout
 load printers = no
 printing = bsd
 printcap name = /dev/null

[Presentations]
 path = /shares/presentations
 browseable = yes
 read only = yes
 guest ok = no
 valid users = @upm_read_only @upm_technician @upm_operator @upm_manager @upm_administrator
 follow symlinks = yes
 wide links = no

[Incoming]
 path = /shares/incoming
 browseable = yes
 read only = no
 guest ok = no
 valid users = @upm_technician @upm_operator @upm_manager @upm_administrator
 force create mode = 0660
 force directory mode = 0770
 veto files = /.upm-*/

[Trash]
 path = /shares/trash
 browseable = yes
 read only = no
 guest ok = no
 valid users = @upm_administrator
