import { useEffect, useState } from "react";
import { siteApi } from "../api/site";
import { Empty, ErrorSurface, Loading } from "../components/Feedback";
import { Page, Panel } from "../components/Page";
import { MediaStatusBadge, formatDate } from "../components/presentationMedia";
import { useApi } from "../hooks/useApi";
const PAGE=50;
export function SitePresentations(){
 const [eventId,setEventId]=useState(""); const [search,setSearch]=useState(""); const [query,setQuery]=useState(""); const [offset,setOffset]=useState(0);
 const events=useApi((signal)=>siteApi.deployments(signal),[]); const active=eventId||events.data?.[0]?.central_event_id||"";
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setOffset(0)},300);return()=>clearTimeout(timer)},[search]);
 const data=useApi((signal)=>active?siteApi.presentationOperations(active,{search:query||undefined,limit:PAGE,offset},signal):Promise.resolve({items:[],total:0,limit:PAGE,offset:0}),[active,query,offset]);
 return <Page eyebrow="Canonical presentation workflow" title="Presentations" description="Confirmed presentations, readiness, and room-delivery state. Readiness and delivery are independent lifecycles."><Panel><div className="media-toolbar"><label>Event<select className="input" value={active} onChange={e=>setEventId(e.target.value)}>{events.data?.map(e=><option key={e.central_event_id} value={e.central_event_id}>{e.event_name||e.central_event_id}</option>)}</select></label><label>Search<input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Identifier or title"/></label></div></Panel>{data.loading?<Loading/>:data.error?<ErrorSurface error={data.error} onRetry={data.refresh}/>:!data.data?.items.length?<Empty title="No presentations"/>:<Panel title={`Presentations (${data.data.total})`}><div className="table-scroll"><table className="data-table"><thead><tr><th>Presenter</th><th>Presentation</th><th>Session / time / room</th><th>Current version</th><th>Readiness</th><th>Room delivery</th><th>Source / received</th><th>Updated</th></tr></thead><tbody>{data.data.items.map(row=><tr key={String(row.presentation_id)}><td>{Array.isArray(row.presenters)?row.presenters.join(", "):"—"}</td><td><strong>{String(row.presentation_identifier)}</strong><small className="block">{String(row.title)}</small></td><td>{String(row.session||"—")}<small className="block">{formatDate(row.starts_at as string)} · {String(row.room||"—")}</small></td><td>{row.current_version?`v${row.current_version}`:"—"}</td><td><MediaStatusBadge value={String(row.readiness)}/></td><td><MediaStatusBadge value={String(row.delivery_state)}/></td><td>{String(row.filename||row.source||"—")}<small className="block">{formatDate(row.received_at as string)}</small></td><td>{formatDate(row.updated_at as string)}</td></tr>)}</tbody></table></div><div className="pagination"><button className="button" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-PAGE))}>Previous</button><span>{offset+1}–{Math.min(offset+PAGE,data.data.total)} of {data.data.total}</span><button className="button" disabled={offset+PAGE>=data.data.total} onClick={()=>setOffset(offset+PAGE)}>Next</button></div></Panel>}</Page>
}
