using Microsoft.Data.Sqlite;
namespace UPM.Windows.Core;

public sealed class LocalStateStore(string databasePath)
{
  string ConnectionString => new SqliteConnectionStringBuilder { DataSource = databasePath, Mode = SqliteOpenMode.ReadWriteCreate }.ToString();
  public async Task InitializeAsync(CancellationToken ct = default) { Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!); await using var db = new SqliteConnection(ConnectionString); await db.OpenAsync(ct); var c = db.CreateCommand(); c.CommandText = """PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS transfer_queue(transfer_id TEXT PRIMARY KEY,profile_id TEXT NOT NULL,event_id TEXT,source_path TEXT NOT NULL,original_filename TEXT NOT NULL,relative_path TEXT NOT NULL,source_volume TEXT,length INTEGER NOT NULL,source_modified TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,state INTEGER NOT NULL,bytes_transferred INTEGER NOT NULL,sha256 TEXT,retry_count INTEGER NOT NULL,retry_at TEXT,error TEXT); CREATE INDEX IF NOT EXISTS ix_transfer_work ON transfer_queue(state,retry_at);"""; await c.ExecuteNonQueryAsync(ct); }
  public async Task EnqueueAsync(TransferItem x, CancellationToken ct = default) { await using var db = new SqliteConnection(ConnectionString); await db.OpenAsync(ct); var c = db.CreateCommand(); c.CommandText = """INSERT INTO transfer_queue VALUES($id,$p,$e,$path,$name,$rel,$vol,$len,$mod,$key,$state,$bytes,$hash,$retry,$at,$error) ON CONFLICT(idempotency_key) DO NOTHING"""; Add(c, "$id", x.TransferId); Add(c, "$p", x.SiteProfileId); Add(c, "$e", x.EventId); Add(c, "$path", x.SourcePath); Add(c, "$name", x.OriginalFilename); Add(c, "$rel", x.RelativePath); Add(c, "$vol", x.SourceVolume); Add(c, "$len", x.Length); Add(c, "$mod", x.SourceModifiedAt); Add(c, "$key", x.IdempotencyKey); Add(c, "$state", (int)x.State); Add(c, "$bytes", x.BytesTransferred); Add(c, "$hash", x.Sha256); Add(c, "$retry", x.RetryCount); Add(c, "$at", x.RetryAt); Add(c, "$error", x.Error); await c.ExecuteNonQueryAsync(ct); }
  public async Task UpdateAsync(Guid id, TransferState state, long bytes = 0, string? hash = null, int retry = 0, DateTimeOffset? retryAt = null, string? error = null, CancellationToken ct = default) { await using var db = new SqliteConnection(ConnectionString); await db.OpenAsync(ct); var c = db.CreateCommand(); c.CommandText = "UPDATE transfer_queue SET state=$s,bytes_transferred=$b,sha256=COALESCE($h,sha256),retry_count=$r,retry_at=$a,error=$e WHERE transfer_id=$id"; Add(c, "$s", (int)state); Add(c, "$b", bytes); Add(c, "$h", hash); Add(c, "$r", retry); Add(c, "$a", retryAt); Add(c, "$e", error); Add(c, "$id", id); await c.ExecuteNonQueryAsync(ct); }
  public async IAsyncEnumerable<TransferItem> LoadPendingAsync([System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct = default) { await using var db = new SqliteConnection(ConnectionString); await db.OpenAsync(ct); var c = db.CreateCommand(); c.CommandText = "SELECT * FROM transfer_queue WHERE state NOT IN ($complete,$cancelled) ORDER BY rowid"; Add(c, "$complete", (int)TransferState.Complete); Add(c, "$cancelled", (int)TransferState.Cancelled); await using var r = await c.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) { yield return new TransferItem(Guid.Parse(r.GetString(0)), Guid.Parse(r.GetString(1)), r.IsDBNull(2) ? null : Guid.Parse(r.GetString(2)), r.GetString(3), r.GetString(4), r.GetString(5), r.IsDBNull(6) ? null : r.GetString(6), r.GetInt64(7), DateTimeOffset.Parse(r.GetString(8)), r.GetString(9), (TransferState)r.GetInt32(10), r.GetInt64(11), r.IsDBNull(12) ? null : r.GetString(12), r.GetInt32(13), r.IsDBNull(14) ? null : DateTimeOffset.Parse(r.GetString(14)), r.IsDBNull(15) ? null : r.GetString(15)); } }
  static void Add(SqliteCommand c, string n, object? v) => c.Parameters.AddWithValue(n, v?.ToString() ?? (object)DBNull.Value);
}
