using System.Security.Cryptography;
using System.Threading.Channels;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using UPM.Windows.Core;
using UPM.Windows.SiteApi;
namespace UPM.Windows.Transfers;

public static class IntakeEnumerator { static readonly HashSet<string> Supported = new(StringComparer.OrdinalIgnoreCase) { ".pptx", ".pptm", ".ppsx", ".pdf", ".mp4", ".mov", ".png", ".jpg", ".jpeg" }; public static async IAsyncEnumerable<TransferItem> EnumerateAsync(IEnumerable<string> roots, Guid profile, Guid? eventId, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct = default) { foreach (var root in roots) { var basePath = Directory.Exists(root) ? root : Path.GetDirectoryName(root)!; var files = Directory.Exists(root) ? Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories) : [root]; foreach (var file in files) { ct.ThrowIfCancellationRequested(); if (!Supported.Contains(Path.GetExtension(file))) continue; var info = new FileInfo(file); yield return new TransferItem(Guid.CreateVersion7(), profile, eventId, file, info.Name, Path.GetRelativePath(basePath, file), Path.GetPathRoot(file), info.Length, info.LastWriteTimeUtc, TransferIdentity.Create(profile, eventId, file, info.Length, info.LastWriteTimeUtc)); await Task.Yield(); } } } }
public interface IRemovableDriveScanner { IAsyncEnumerable<DriveInfo> WatchAsync(CancellationToken ct); IAsyncEnumerable<TransferItem> ScanAsync(DriveInfo drive, Guid profile, Guid? eventId, CancellationToken ct); }
public sealed class TransferWorker(LocalStateStore store, SiteApiClient api, ILogger<TransferWorker> log) : BackgroundService
{
  readonly Channel<TransferItem> queue = Channel.CreateBounded<TransferItem>(new BoundedChannelOptions(256) { FullMode = BoundedChannelFullMode.Wait }); public ValueTask QueueAsync(TransferItem x, CancellationToken ct) => queue.Writer.WriteAsync(x, ct);
  protected override async Task ExecuteAsync(CancellationToken stoppingToken) { await foreach (var item in store.LoadPendingAsync(stoppingToken)) await queue.Writer.WriteAsync(item with { State = TransferState.Queued }, stoppingToken); var workers = Enumerable.Range(0, 4).Select(_ => Run(stoppingToken)); await Task.WhenAll(workers); }
  async Task Run(CancellationToken ct) { await foreach (var item in queue.Reader.ReadAllAsync(ct)) { try { await store.UpdateAsync(item.TransferId, TransferState.Hashing, ct: ct); string hash; await using (var file = new FileStream(item.SourcePath, FileMode.Open, FileAccess.Read, FileShare.Read, 1024 * 1024, FileOptions.Asynchronous | FileOptions.SequentialScan)) { hash = Convert.ToHexString(await SHA256.HashDataAsync(file, ct)).ToLowerInvariant(); file.Position = 0; await store.UpdateAsync(item.TransferId, TransferState.Uploading, hash: hash, ct: ct); using var response = await api.UploadAsync(item, file, ct); response.EnsureSuccessStatusCode(); } await store.UpdateAsync(item.TransferId, TransferState.ReceivedBySite, item.Length, hash, ct: ct); } catch (OperationCanceledException) when (ct.IsCancellationRequested) { break; } catch (Exception e) { var retries = item.RetryCount + 1; var delay = TimeSpan.FromSeconds(Math.Min(300, Math.Pow(2, retries)) + Random.Shared.NextDouble()); await store.UpdateAsync(item.TransferId, TransferState.RetryWaiting, retry: retries, retryAt: DateTimeOffset.UtcNow + delay, error: e.Message, ct: ct); log.LogWarning(e, "Transfer {TransferId} will retry", item.TransferId); } } }
}
