<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../UPM.Windows.Core/UPM.Windows.Core.csproj"/><ProjectReference Include="../UPM.Windows.SiteApi/UPM.Windows.SiteApi.csproj"/><PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0"/></ItemGroup></Project>
